### PR TITLE
8주차 문제 풀이 - Queue-ri

### PR DESCRIPTION
**Pull request by Queue-ri**
### Review
- [택배 배송](https://til.qriosity.dev/featured/ps/boj/5972)
- [파티](https://til.qriosity.dev/featured/ps/boj/1238)
- [서강그라운드](https://til.qriosity.dev/featured/ps/boj/14938)

### CODE REVIEW

**Review by C-H-Kim — APPROVED** [review]
## LGTM
고생하셨습니다!

**Review by dckat — APPROVED** [review]
# LGTM
***
고생하셨습니다!

**Review by DHKim96 — APPROVED** [review]
## LGTM
고생하셨습니다!

**Review by HeeJava — APPROVED** [review]
### **LGTM**

대단하십니다 ㅎㅎ

**Pull request merged**
