### PR TITLE
1주차 문제 풀이 - Queue-ri

### PR DESCRIPTION
**Pull request by Queue-ri**
### Review
- [구간 합 구하기 5](https://til.qriosity.dev/featured/ps/boj/11660)
- [치킨 배달](https://til.qriosity.dev/featured/ps/boj/15686)
- [A와 B 2](https://til.qriosity.dev/featured/ps/boj/12919)

### CODE REVIEW

**Review by DHKim96 — APPROVED** [review]
LGTM

**Review by C-H-Kim — APPROVED** [review]
## LGTM
고생하셨습니다!

**Review by dckat — APPROVED** [review]
## LGTM
 확인했습니다!

**Review by juil1-kim — APPROVED** [review]
### LGTM
수고하셨습니다~

**Pull request merged**
